source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails', '4.2.1'

gem 'pg'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'slim-rails'

gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'

gem 'dotenv-rails'

gem "sorcery"

gem "bower-rails", "~> 0.10.0"

gem "wicked"
gem 'carmen-rails'

group :development, :test do
  gem 'pry-rails'
  gem "letter_opener"
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 3.0'
  gem 'selenium-webdriver', '2.45.0'
  gem 'factory_girl_rails'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'
