# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
#
=begin
edition = Edition.create(start_date: DateTime.new(2016, 2, 15), end_date: DateTime.new(2016, 5, 8), name: "second")
Week.create(start: DateTime.new(2016, 2, 15), end: DateTime.new(2016, 2, 21), number: 1, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 2, 22), end: DateTime.new(2016, 2, 28), number: 2, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 2, 29), end: DateTime.new(2016, 3, 6), number: 3, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 3, 7), end: DateTime.new(2016, 3, 13), number: 4, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 3, 14), end: DateTime.new(2016, 3, 20), number: 5, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 3, 21), end: DateTime.new(2016, 3, 27), number: 6, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 3, 28), end: DateTime.new(2016, 4, 3), number: 7, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 4, 4), end: DateTime.new(2016, 4, 10), number: 8, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 4, 11), end: DateTime.new(2016, 4, 17), number: 9, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 2, 18), end: DateTime.new(2016, 4, 24), number: 10, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 4, 25), end: DateTime.new(2016, 5, 1), number: 11, edition_id: edition.id)
Week.create(start: DateTime.new(2016, 5, 2), end: DateTime.new(2016, 5, 8), number: 12, edition_id: edition.id)

EmailTemplate.create(
subject: "[Learn IT, Girl] Mentor application results",
recipients: 10,
body: "Dear %{first_name},\r\n\r\nIt has been great to have you applying to “Learn IT, Girl” second edition. We really liked your motivation and passion for helping a girl learn IT. However, we currently don’t have a mentee to match you with. This is not the end! We will have you on our waiting list in case we find a suitable mentee for you during the programme.\r\n\r\nMeanwhile, you can still help mentees through our <a href=\"https://www.facebook.com/groups/learnitgirl/\" target=\"_blank\">Facebook group</a>, helping answering questions they might have. \r\n\r\nWe would also love you to give us feedback on our application process. You can fill in <a target=\"_blank\"href=\"https://docs.google.com/forms/d/1jMiiq3m2KYutFB4ANTJKmOrzm8uqBeadhgQKEdB9_Co/viewform?c=0&w=1\">this survey</a> telling us what you think about our application process so we can make it better next time.\r\n\r\nKind regards,\r\n<i>The \"Learn IT, Girl!\" team</i>\r\n<a href=\"http://www.learnitgirl.com/\" target=\"_blank\">\"Learn IT, Girl\"</a> | <a href=\"https://twitter.com/learnitgirl\" target=\"_blank\">Follow us on Twitter </a>| <a href=\"https://www.facebook.com/learnitgirl/\" target=\"_blank'>Like us on Facebook </a>| <a href=\"https://learnitgirl.wordpress.com/\" target=\"_blank\">Read our blog</a>"
)


EmailTemplate.create(
  subject: "[Learn IT, Girl] Welcome as a second edition mentor!",
  recipients: 2,
  body: "Dear %{first_name},\r\n\r\nThank you for applying to “Learn IT, Girl” second edition! We are very excited to announce that you are accepted as a mentor. Congratulations! We are happy to have you with us helping us change the trend in IT.\r\n\r\nYour mentee will be %{mentee_full_name}. Her email is %{mentee_email}. She is from %{mentee_country} and she wants to work on:\r\n%{project_description}\r\n\r\nThe next step is to confirm your participation in the program and create an account by clicking here <a href=%{registration_link} target=\"_blank\">link</a>. Please have a look at the <a href=\"https://www.learnitgirl.com/mentor_dos_and_donts\" target=\"_blank\">Dos and Don’ts for mentors </a> and <a href=\"https://www.learnitgirl.com/mentee_dos_and_donts\" target=\"_blank\">scholars</a> before you contact your mentee. You should schedule a Hangout/Skype session with your mentee to work together on a final project and description. Once you have agreed on them, your mentee will be able to update them on her profile (do so during this first week as it will get blocked afterwards). You will also need to work on a roadmap for the next 12 weeks, including weekly tasks that you will add to your dashboard on the LITG website. You can check a roadmap example <a href=\"https://www.learnitgirl.com/roadmap_example\" target=\"_blank\">here</a>.\r\n\r\nYour mentee and you will be using git to communicate. If you would like to refresh your git skills, you can check <a href=\"http://www.learnitgirl.com/learning_materials/git\" target=\"_blank\">this tutorial</a>.\r\n\r\nIf you haven’t already, we invite you to join the <a href=\"https://www.facebook.com/groups/learnitgirl/\" target=\"_blank\"> LITG Facebook scholar group </a> and the <a href=\"https://www.facebook.com/groups/learnitgirl.mentors/\" target=\"_blank\"> LITG mentor group</a>. These will be great places to socialize and share experiences.\r\n\r\nWe would also love you to give us feedback on our application process. You can fill in <a target=\"_blank\"href=\"https://docs.google.com/forms/d/1jMiiq3m2KYutFB4ANTJKmOrzm8uqBeadhgQKEdB9_Co/viewform?c=0&w=1\">this survey</a> telling us what you think about our application process so we can make it better next time.\r\n\r\nWe're looking forward to hearing from you! Thank you so much for your involvement!\r\n\r\nKind regards,\r\n<i>The \"Learn IT, Girl!\" team</i>\r\n<a href=\"http://www.learnitgirl.com/\" target=\"_blank\">\"Learn IT, Girl\"</a> | <a href=\"https://twitter.com/learnitgirl\" target=\"_blank\">Follow us on Twitter </a>| <a href=\"https://www.facebook.com/learnitgirl/\" target=\"_blank'>Like us on Facebook </a>| <a href=\"https://learnitgirl.wordpress.com/\" target=\"_blank\">Read our blog</a>"
)

Emailtemplate.create(
  subject: "[Learn IT, Girl] Mentor application results",
  recipients: 11,
   body: "Dear %{first_name},\r\n\r\nIt has been great to have you applying to “Learn IT, Girl” second edition. We have had a big number of applications to evaluate and we have valued motivation, communication skills and details in the answers. Unfortunately, your application hasn’t been successful, mostly due to the shortness in the answers, so we will not be able to accept you at “Learn IT, Girl” this time. \r\n\r\nEven if you didn’t get accepted this time, we loved the fact that you applied to join us! Don’t get discouraged! We love the fact that you want to mentor other to help them learn IT. You can still help mentees through our <a href=\"https://www.facebook.com/groups/learnitgirl/\" target=\"_blank\">Facebook group </a>, helping answering questions they might have. \r\n\r\nWe would also love you to give us feedback on our application process. You can fill in <a target=\"_blank\"href=\"https://docs.google.com/forms/d/1jMiiq3m2KYutFB4ANTJKmOrzm8uqBeadhgQKEdB9_Co/viewform?c=0&w=1\">this survey</a> telling us what you think about our application process so we can make it better next time.\r\n\r\nKind regards,\r\n<i>The \"Learn IT, Girl!\" team</i>\r\n<a href=\"http://www.learnitgirl.com/\" target=\"_blank\">\"Learn IT, Girl\"</a> | <a href=\"https://twitter.com/learnitgirl\" target=\"_blank\">Follow us on Twitter </a>| <a href=\"https://www.facebook.com/learnitgirl/\" target=\"_blank'>Like us on Facebook </a>| <a href=\"https://learnitgirl.wordpress.com/\" target=\"_blank\">Read our blog</a>"
)

EmailTemplate.create(
  subject: "[Learn IT, Girl] Congratulations! Welcome as a second edition mentee. Action required",
  recipients: 0,
  body: "Dear %{first_name},\r\n\r\nThank you for applying to “Learn IT, Girl” second edition! We are very excited to announce that you are accepted as a scholar. Congratulations! We are happy to have you with us learning IT and being part of our community.\r\n\r\nYour mentor will be %{mentor_full_name}. They are from %{mentor_country} and their email is %{mentor_email}.\r\n\r\nThe next step is to confirm your participation in the program and create an account by clicking <a href=%{registration_link} target=\"_blank\">here</a> Please have a look at the <a href=\"https://www.learnitgirl.com/mentee_dos_and_donts\" target=\"_blank\">Dos and Don’ts</a> before contacting your mentor. You should schedule a Hangout/Skype session with them to work together on a final project and description. Once you have agreed on them, you will be able to update them on your profile (do so during this first week as it will get blocked afterwards). You will also need to work on a roadmap for the next 12 weeks, including weekly tasks that you will add to your dashboard on the LITG website. You can check a roadmap example <a href=\"#\" target=\"_blank\">here</a>.\r\n\r\nIf you haven’t already, we invite you to join the <a href=\"https://www.facebook.com/groups/learnitgirl/\" target=\"_blank\">LITG Facebook scholar group</a>. It will be a great place to socialize and share experiences.\r\n\r\nWe would also love you to give us feedback on our application process. You can fill in <a href=\"https://docs.google.com/forms/d/1K6i_vy_8_aC1EXL1TzprN5QGxIC52lO8BPcTiF_2hZM/viewform?usp=send_form\" target=\"_blank\">this survey</a> telling us what you think about our application process so we can make it better next time.\r\n\r\nWe're looking forward to hearing from you! Thank you so much for your involvement!\r\n\r\nKind regards,\r\n<i>The \"Learn IT, Girl!\" team</i>\r\n<a href=\"http://www.learnitgirl.com/\" target=\"_blank\">\"Learn IT, Girl\"</a> | <a href=\"https://twitter.com/learnitgirl\" target=\"_blank\">Follow us on Twitter </a>| <a href=\"https://www.facebook.com/learnitgirl/\" target=\"_blank'>Like us on Facebook </a>| <a href=\"https://learnitgirl.wordpress.com/\" target=\"_blank\">Read our blog</a>\r\n"
)
=end

EmailTemplate.create(
  subject: "[Learn IT, Girl] Mentee application results",
  recipients: 1,
  body: "Dear %{first_name},\r\n\r\nIt has been great to have you applying to “Learn IT, Girl” second edition. We have had a big number of applications to evaluate and we have valued motivation, communication skills and details in the answers. Unfortunately, your application hasn’t been successful, mostly due to the shortness in the answers, so we will not be able to accept you at “Learn IT, Girl” this time.\r\n\r\nEven if you didn’t get accepted this time, we loved the fact that you applied to join us! Don’t get discouraged! We love the fact that you want to learn IT and work on a project. You can still join <a href=\"https://www.facebook.com/groups/learnitgirl/\" target=\"_blank\"> our Facebook group </a> and be part of our community.\r\n\r\nWe would also love you to give us feedback on our application process. You can fill in <a target=\"_blank\"href=\"https://docs.google.com/forms/d/1K6i_vy_8_aC1EXL1TzprN5QGxIC52lO8BPcTiF_2hZM/viewform?usp=send_form\">this survey</a> telling us what you think about our application process so we can make it better next time.\r\n\r\nKind regards,\r\n<i>The \"Learn IT, Girl!\" team</i>\r\n<a href=\"http://www.learnitgirl.com/\" target=\"_blank\">\"Learn IT, Girl\"</a> | <a href=\"https://twitter.com/learnitgirl\" target=\"_blank\">Follow us on Twitter </a>| <a href=\"https://www.facebook.com/learnitgirl/\" target=\"_blank'>Like us on Facebook </a>| <a href=\"https://learnitgirl.wordpress.com/\" target=\"_blank\">Read our blog</a>\r\n"
)
